sudo: false
language: python
dist: bionic
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - env: TOX_ENV=py36
      python: 3.6
      name: "Python 3.6"
    - env: TOX_ENV=py37
      python: 3.7
      name: "Python 3.7"
    - env: TOX_ENV=py38
      python: 3.8
      name: "Python 3.8"
    - env: TOX_ENV=type-checking
      python: 3.6
      name: "Python 3.6 Type checks"
    - env: TOX_ENV=type-checking
      python: 3.7
      name: "Python 3.7 Type checks"
    - env: TOX_ENV=type-checking
      python: 3.8
      name: "Python 3.8 Type checks"
    - env: TOX_ENV=lint
      python: 3.6
      name: "Python 3.6 Linter checks"

install:
  - pip3 install --upgrade pip "poetry>=1.1.0" tox
script: travis_retry tox -e $TOX_ENV
before_deploy:
    - poetry build
deploy:
  provider: pypi
  user: ashleysommer
  skip_cleanup: true #Need skip cleanup because we build the artifacts in before_deploy
  password:
    secure: fakestring
  on:
    tags: true
    python: 3.6
    condition: $DEPLOY = true
    branch: release
  distributions: "sdist bdist_wheel"
  skip_existing: true
